Appease nay
anlutro/botologist pull request #82
Opened 2017-03-10 19:06 UTC by x89

2017-03-10 19:07 UTC, anlutro commented
Hey I'm kinda busy right now, I'll get back to this in 3 weeks or so

2017-03-29 12:52 UTC, x89 commented
Please that's almost 3 weeks @anlutro!

2017-03-29 12:54 UTC, anlutro commented
Hmmm there are conflicts, could you have a look @x89 ?

2017-03-29 13:00 UTC, EricBisceglia requested changes
Forgot capitalisation of « Naypam »

2017-03-29 13:10 UTC, x89 commented
Conflict status: solved!

2017-08-30 13:31 UTC, EricBisceglia commented
This change should be reverted imo.

2017-08-30 13:38 UTC, anlutro commented
> This change should be reverted imo.
Done, thanks for letting me know

There are conflicts again!

2025-07-29 09:25 UTC, closed without merging